version: 2

project_name: PROJECT_NAME

builds:
  - id: server
    env: &env
      - CGO_ENABLED=0
    goos: &srv_goos
      - linux
    goarch: &goarch
      - arm64
    goarm: &goarm
      - "7"
    binary: PROJECT_NAME-server
    dir: ./cmd/server/
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: &ldflags
      - -X=github.com/OWNER/PROJECT_NAME/internal/cli/cmd.Version={{.Version}}
      - -X=github.com/OWNER/PROJECT_NAME/internal/cli/cmd.Commit={{.Commit}}
      - -X=github.com/OWNER/PROJECT_NAME/internal/cli/cmd.Date={{ .CommitDate }}

  - id: cli
    dir: ./cmd/cli/
    binary: PROJECT_NAME-cli
    goos:
      - darwin
    env: *env
    goarch: *goarch
    goarm: *goarm
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: *ldflags

archives:
  - id: server
    ids:
      - server
    name_template: 'PROJECT_NAME_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

  - id: cli
    ids:
      - cli
    name_template: 'PROJECT_NAME_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
